d = input('Digite algo:')
print('O tipo primitivo desse valor é', type(d))
print(f'é numerico?{d.isnumeric()}')
print(f'é alfanumerico?{d.isalnum()}')
print(f'só tem Espaços? {d.isspace()}')
print(f'Tem alfabeto? {d.isalpha()}')
print(f'Esta em Maiusculo? {d.isupper()}')
print(f'Esta em Minusculo? {d.islower()}')
print(f'Esta Capitalizado?{d.istitle()}')
print(f'É um numero Decimal?{d.isdecimal()}')